version: '3'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./configAsCode.yaml:/var/jenkins_home/casc.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      JENKINS_ADMIN_PASSWORD: ${JENKINS_ADMIN_PASSWORD}
      JENKINS_ADMIN_ID: ${JENKINS_ADMIN_ID}
      JENKINS_HOST: ${JENKINS_HOST}
      GITHUB_REPO_JOB_DSL: ${GITHUB_REPO_JOB_DSL}
volumes:
  jenkins_home: